### ISSUE TITLE
Implement dependency service

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#140]
Hello,
I think It would be nice to follow best practices and implement dependency service.
As it is implemented here: https://developer.xamarin.com/guides/xamarin-forms/dependency-service/battery-info/

**Comment by JeanCollas** [comment]
What would you delegate to the dependency service?

**Comment by deextercz** [comment]
I think at least maprenderer is s good candidate

**Comment by JeanCollas** [comment]
How would it simplify something? (I don't know if it is a good or bad thing, just trying to understand :) )
I would just avoid linking the X.F.GoogleMaps.Android to the main .Droid project? (and same for iOS)

**Comment by deextercz** [comment]
1. Advantage it would be easier to test
2. You dont need have instance of object DI will provide to you.

**Comment by JeanCollas** [comment]
Hum I thought it was the same as in ASP.Net, where you need to register the type, but it seems in Xamarin it autoregisters with the class attribute 
[assembly: Dependency(typeof(BatteryImplementation))]

But I believe the reason why Maps is beeing loaded is because of the linker, that would not load link the types otherwise. I haven't tried, but are you sure it would not be an issue if moved to DI? (as moving to DI would be, I guess, to move the init code to the common project). Also still need to handle differently the initiation for Android and iOS (iOS requires a key?)

**Comment by amay077** [comment]
I don't know different from [battery-info](https://developer.xamarin.com/guides/xamarin-forms/dependency-service/battery-info/) to current implementation.

DependencyService is already used in X.F.GoogleMaps.
https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps.Android/Properties/AssemblyInfo.cs#L23

What is the point of your suggestion?
