### ISSUE TITLE
get_Map() not found when Linker set to "SDK Assemblies only"

### ISSUE THREAD

**Issue by SvenCarstensen** [amay077/Xamarin.Forms.GoogleMaps#163]
Hi,

if i set the Linker at Release config to "SDK Assemblies only, i get the following error:

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: Error: Error executing task LinkAssemblies: error XA2006: Reference to metadata item 'Android.Gms.Maps.GoogleMap Android.Gms.Maps.MapView::get_Map()' (defined in 'Xamarin.Forms.GoogleMaps.Android, Version=1.7.0.6, Culture=neutral, PublicKeyToken=null') from 'Xamarin.Forms.GoogleMaps.Android, Version=1.7.0.6, Culture=neutral, PublicKeyToken=null' could not be resolved. (Assecutor_Shared.Android)

When set to "Don't link" everything builds fine.

**Comment by SvenCarstensen** [comment]
Hi, 

i have think i have found the reason why it works in some projects.

Linking will work with GooglePlayServices version 29.0.0.2.
If a newer version is in use, the linker error occurs.

Regards Sven.

**Comment by SvenCarstensen** [comment]
Hi,

quick and dirty solution:

1) Get source
2) Open MapViewExtension
3) Comment out in GetGoogleMapAsync

            try
            {
                var googleMap = GetMap(self);

                if (googleMap != null)
                {
                    return Task.FromResult(googleMap);
                }
            }
            catch (MissingMethodException)
            {
            }

and remove 

            static GoogleMap GetMap(MapView mapView)
            {
#pragma warning disable CS0618 // Type or member is obsolete
                 return mapView.Map;
#pragma warning restore CS0618 // Type or member is obsolete
            }

4) Now compile and use this .dll in your project.

There is definitely a much better solution, but this is sufficient for me only once.

Regards Sven.

**Comment by amay077** [comment]
Xamarin Google Play Services ver.32.x can not use with Xamarin.Forms latest ver.
Because Xamarin.Forms 2.3.3 depends Xamarin.Android.Support.v4 ver23.3.0 only, 
but Xamarin Google Play Services 32.x needs greater than Xamarin.Android.Support.v4 ver24.2.1.

## Xamarin.Forms 2.3.3.175

![2017-01-03 22 55 05](https://cloud.githubusercontent.com/assets/401369/21609828/f545f846-d207-11e6-806d-5d8d15f9872c.png)

## Xamarin Google Play Services - Basement 32.961.0

![2017-01-03 22 54 49](https://cloud.githubusercontent.com/assets/401369/21609836/fcd3253e-d207-11e6-9aee-15965acfa5cc.png)
