### ISSUE TITLE
Can I add the dotted line to the map?

### ISSUE THREAD

**Issue by non335** [amay077/Xamarin.Forms.GoogleMaps#188]
Like in the google map when I change travel mode to walking.

![5ee07c54-d26a-4042-8b98-e2dbe231ab7d](https://cloud.githubusercontent.com/assets/10905991/22429940/01bef536-e73f-11e6-820f-e9ceec5e5da7.jpg)

Thank you in advance

**Comment by amay077** [comment]
Hi @non335 ,

Can not draw "dotted line" because [Native Google Maps API](https://developers.google.com/android/reference/com/google/android/gms/maps/model/Polyline) has only line-width and color.

**Comment by davidmclennan** [comment]
Sorry if I'm not understanding, but does that link not imply this should be possible through the Stroke Pattern property?

**Comment by amay077** [comment]
Oh, Stroke  Pattern is newbie at [February 15, 2017](https://developers.google.com/maps/documentation/android-api/releases#february_15_2017),
We can't use these properties yet.
Because Xamarin.Forms 2.3.3.x depends [June 27, 2016](https://developers.google.com/maps/documentation/android-api/releases#june_27_2016) released library.

I hope we can use latest Google Maps API in Xamarin.Forms 2.3.4.x.

**Comment by amay077** [comment]
I can implementing this issue by #239 .
Wait a while.

**Comment by galadril** [comment]
Any news on this feature request?

**Comment by amay077** [comment]
Not yet. 🙏

**Comment by amay077** [comment]
Move to #470
