### ISSUE TITLE
The map scrolling freezes after moving map region using Xamarin.Forms.GoogleMaps.Bindings

### ISSUE THREAD

**Issue by LuisDeHaro** [amay077/Xamarin.Forms.GoogleMaps#418]
### SUMMARY

The map scrolling freezes after moving map region using Xamarin.Forms.GoogleMaps.Bindings

### VERSIONS

* Xamarin.Forms.GoogleMaps - 2.2.1
* Xamarin.Forms - 2.3.4.247
* Xamarin.Forms.GoogleMaps.Bindings - 2.1.0

### PLATFORMS

- [x] Android
- [ ] iOS
- [ ] UWP

### HOW TO REPRODUCE

(Let me show how to reproduce with steps or codes)

1. Open a page with a map (Map region moved programmatically MVVM)
2. Scroll map without zoom (Everything works just fine)
3. Zoom in the map
4. Scroll the map again and it will freeze for a while and then will start to work fine again

```xml
<googleMaps:Map 
	x:Name="map" 
	CameraIdled="Handle_CameraIdled" 
	CameraMoveStarted="Handle_CameraMoveStarted"  
	VerticalOptions="FillAndExpand" 
	HorizontalOptions="FillAndExpand"  
	HasZoomEnabled="true"  
	HasScrollEnabled="true">
	<googleMaps:Map.Behaviors>
		<bindings:MoveToRegionBehavior Request="{Binding Request}"/>
		<bindings:BindingVisibleRegionBehavior Value="{Binding VisibleRegion}"/>
	</googleMaps:Map.Behaviors>
</googleMaps:Map>
```

```csharp
public MoveToRegionRequest Request { get; } = new MoveToRegionRequest();

private MapSpan _visibleRegion;
public MapSpan VisibleRegion
{
	get
	{
		return _visibleRegion;
	}
	set
	{
		_visibleRegion = value; 
		RaisePropertyChanged("VisibleRegion");
	}
}

this.Request.MoveToRegion(
	this.MapSpan.FromCenterAndRadius(
		new Position(this.latitude, this.longitude),
		Distance.FromMeters(350)
	)
);

```

### ACTUAL IMAGES

Please find below a screen capture of the issue (GIF)

![Screen capture](https://media.giphy.com/media/xT0xezSNh1OtAOfguk/giphy.gif)

**Comment by amay077** [comment]
Is this Xamarin.Forms.GoogleMaps.Bindings's bug?

@stringo , Could you reproduce this using only Xamarin.Forms.GoogleMaps?

**Comment by nuitsjp** [comment]
There is a code similar to the sample of GoogleMaps.Bindings, but this is working properly.
https://github.com/nuitsjp/Xamarin.Forms.GoogleMaps.Bindings/blob/master/Sample/GoogleMaps.Bindings/GoogleMaps.Bindings/Views/VisibleRegionPage.xaml

One thing that I care about is that I do not know how to call MoveToRegion.
Will you be calling each time VisibleRegion is changed?

Please build this sample application and check that "VISIBLE REGION" works properly
https://github.com/nuitsjp/Xamarin.Forms.GoogleMaps.Bindings

If it does not work properly, it is one of the following problems.
1. Bugs in Xamarin.Forms.GoogleMaps.Bindings
2. Somewhat different between your environment and my environment

If it works correctly, you probably have a cause in your code.
Since you can not analyze with code sample alone, please provide the minimum code to reproduce the phenomenon.

Thank you.

**Comment by stringo** [comment]
@amay077 @nuitsjp 

Thanks for your response guys, I will try nuitsjp's suggestion and will update here once I've completed the tests.
