### ISSUE TITLE
Location ID Number For Map Pins

### ISSUE THREAD

**Issue by BillyMartin1964** [amay077/Xamarin.Forms.GoogleMaps#523]
Could you please add an ID property of type int to the map pins so that we can identify which location pin is being manipulated? It would make it so much easier. Thank you.

**Comment by amay077** [comment]
Sorry I can not provide it.
Because original Google Maps SDK does not have ``marker.Id``.

* [Android](https://developers.google.com/android/reference/com/google/android/gms/maps/model/Marker.html)
* [iOS](https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_marker)

(Android's ``maker.getId()`` is not settable(auto generated string).)

Alternately, you can use ``Pin.Tag`` property.
