### ISSUE TITLE
Load images instead of Google Maps

### ISSUE THREAD

**Issue by AnthonyLatty** [amay077/Xamarin.Forms.GoogleMaps#602]
Can i load a regular .png or .jpg image instead of its base64? The image i am trying to load its base64 format is too large to load in the app but its regular format loads when i place the same image in a `Image` control instead of a `Map` control.

**Comment by Sonnenspeer** [comment]
Depends on the size. If you can split it up and it takes place more than two or three tiles of the map then I would create a tiles provider for it. Otherwise try to decode the base64 string to an Bitmap image and then scale it down. Best would be if the image would already been scaled down or permanently cached anywhere after scaling and the reuse this smaller image.

**Comment by AnthonyLatty** [comment]
The image is 850kb after resize and compression when i convert it to a base64 format it duplicates the image on the screen
