### ISSUE TITLE
Get coordinates and bearing if MyLocationEnabled is set to true

### ISSUE THREAD

**Issue by woemike** [amay077/Xamarin.Forms.GoogleMaps#689]
### SUMMARY

I would like to get location coordinates and bearing if MyLocationEnabled = true.

### DETAILS

An event like OnLocationChanged() which will provide coordinates of location + bearing

### PLATFORMS

- [x] Android
- [ ] iOS
- [ ] UWP

**Comment by amay077** [comment]
We can't support it because ``OnMyLocationChangeListener`` in Google Maps SDK for Android does not support.

https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.OnMyLocationChangeListener.html 

I have a plan to ``LocationSource`` support that can using your own location source.

https://developers.google.com/android/reference/com/google/android/gms/maps/LocationSource
