### ISSUE TITLE
How to disable map marker click auto center?

### ISSUE THREAD

**Issue by ufukhawk** [amay077/Xamarin.Forms.GoogleMaps#718]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.3.0
* Xamarin.Forms - 4.6.0

### PLATFORMS

- [x] Android
- [x] iOS
- [ ] UWP

### ACTUAL BEHAVIOR

When I click on any pin on the map, it automatically comes to the middle of the map, how can I prevent this?

Because when the map moves, I request the service to create new pins. When I click on the pin, the informative popup disappears because the map moves.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30172226/84644731-3ad72980-af08-11ea-94ea-a99dda73268d.gif)

**Comment by ufukhawk** [comment]
if(lastSelectedPin!=null)
                foreach (var pin in  map.Pins)
                {
                    if(pin== lastSelectedPin)
                    {
                        map.SelectedPin = pin;
                    }
                }

**Comment by PaulC-ManyHats** [comment]
I'm having a similar issue, I noticed you closed this, did you manage to prevent the map from moving when a pin is tapped (I'm a couple of years late here)? I don't want the map to move but I do want the info window to popup.

**Comment by PaulC-ManyHats** [comment]
Ok I found it:

```
protected override void OnMapPinClicked(object sender, PinClickedEventArgs e)
{
            e.HideInfoWindow = true;
}
```

**Comment by boris-df** [comment]
Hey, @PaulC-ManyHats - Where exactly did you put this code? I can't find such function to override it. 
Also: How is "HideInfoWindow = true" SHOWING the Info Window? :D - and how is this suppressing the Map-Movement?

I have the exact same problem: As soon as the Map moves, i'm loading new Pins which causes the popup to go away.
I cannot simple memorize the selected pin as i'm building clusters and if the map is moved, the clusters are build from scratch because new data can be available then - so my pins are not neccessarily the "same" after a map-move ...

I would like the Map to NOT MOVE if a Pin is tapped ...

**Comment by boris-df** [comment]
> SelectedPin

Where do you have this property? Was this in an old version and now it's gone? The Map-Class i have doesn't have such property. Do you still use this workaround?
