### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by marcioqmaciel** [amay077/Xamarin.Forms.GoogleMaps#766]
Hi @amay077 

First, thank you for your wonderful project. Only now is the XF team including some things present in yours. But it's been 7 months since the last beta, which we're all waiting for because of Google's new policies.

Do you still intend to be in charge of the project? Can we seriously consider forking and continuing from your beta onwards?

Hugs from Brazil.

**Comment by LittleBoxOfChicken** [comment]
I would also like to know this, actually.

In my personal opinion, I wouldn't be surprised. The entire Xamarin.Forms framework has been dying for a long time now.

**Comment by themronion** [comment]
Well if it is not yet dead, then it will soon become dead because of MAUI. So if someone has the guts to rewrite the library - it would be amazing, because the regular Xamarin.Forms.Maps still doesn't have all the goodies

**Comment by LittleBoxOfChicken** [comment]
@themronion 

Going a bit off-topic with this but since this thread is not really active I thought I'd ask:

What do you think about MAUI? In my personal opinion it's basically Xamarin 6, I think it's going to be just as bad and that it still has a long way to go until it can compete with Flutter.

Any opinions?

**Comment by themronion** [comment]
@LittleBoxOfChicken it is too early to say, but i am quite optimistic about it, i mean they are almost rewriting all the controls from ground up + simplifying working with resources and much MUCH more. Definitely this is not considered as Xamarin 6. Of course it will be hard to compete with Flutter, but who said that life is easy? So, until we see it released there is not much we can argue about)

**Comment by LittleBoxOfChicken** [comment]
>So, until we see it released there is not much we can argue about

True, although the biggest issue we have with Xamarin is the fact that it always tries to use native controls. Which, for us, always results in platform inconsistencies en specific per-platform implementations which take up a lot of time.

This however is confirmed to not change for MAUI.

**Comment by themronion** [comment]
@LittleBoxOfChicken that is the point of xamarin to use native controls, and not drawn controls as flutter)

**Comment by marcioqmaciel** [comment]
There are pros and cons to each approach:

doing your own control takes more work, but more freedom

using native control means using something already ready and functional, but it ends up being a limiter as it must be the common denominator across all platforms

ex:
use Android map + iOS map + UWP map + ... the same feature must be present on the 3 platforms (limitation)

or
create a map control, create a map SERVICE (MS is still in that boat?), make this service used, updated ...

**Comment by marcioqmaciel** [comment]
Example:

The UWP.Map control allows you to download and use maps offline, through C#. The Android.Map control does not allow it. So, when choosing the approach of using native controls, the Xamarin.Map control may not have the option to download maps offline.

The point is: does anyone trust Microsoft for map services?

Pros and cons.

**Comment by LittleBoxOfChicken** [comment]
> using native control means using something already ready and functional, but it ends up being a limiter as it must be the common denominator across all platforms.

And you hope it stays functional too. Because with every update of any platform, your implementation could and sometimes **must** change. Which means you are still forever bound to each individual platform's implementation of every single control. That is a huge caveat for a framework that calls itself "cross platform". 

> doing your own control takes more work, but more freedom

The freedom that you win in this case is the freedom to alter the behavior of each control on each platform individually. Going native would be a much more logical approach if your project requires this.
On top of that, you usually only do this because Xamarin or the package that you are using was unable to unify the specific behavior that you require for each platform, hence you are left to do it yourself.

In the end, my point being. Flutter is a much more timely approach to cross-platform development because instead of adding more and more code to unify each platform as much as possible, it uses a platform that is unified in itself, providing a much more stable base for the developers.

Also as a side note, if your app requires gestures or control-altering animations I'd definitely steer clear of Xamarin.

**Comment by themronion** [comment]
https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/783#issuecomment-1169920397

**Comment by amay077** [comment]
Hello everyone.
I'm reborn. :innocent:

(I was writing typescript for several years.
So I lost interest in Xamarin and C#.
But recently I re-started writing C#, which has given me some motivation.)

This project is not died.
I'm deployed [v5.0.0 to nuget](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/5.0.0) that supports Xamarin.Forms 5.0.
And I'm starting understand for MAUI, I will supports it if I can(maybe create new project)。.
