### ISSUE TITLE
.Net Maui Support

### ISSUE THREAD

**Issue by HobDev** [amay077/Xamarin.Forms.GoogleMaps#783]
Does .NET Maui support is on the roadmap. When the package is expected to be ready for .NET Maui

**Comment by jari-kuipers** [comment]
No, MAUI support is not on the roadmap. The only way this package will be moved to MAUI is if someone else forks this.

**Comment by jari-kuipers** [comment]
This question was already asked by yours truly in [#772](https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/772)

**Comment by HobDev** [comment]
@amay077 Can you guide the community for the migration to .NET MAUI. You have requisite knowledge about the Maps. Can you answer few questions. What needs to be learn. where to find the resources.  What can be taken from this package and what new needs to be added. What are the main obstacles in the migration.
Many developers including me would like to migrate the package but don't have the knowledge. Your help is critical in this endeavor.

**Comment by themronion** [comment]
Hey guys. Made a Maui version, check out on your spare time (maui branch): https://github.com/themronion/Maui.GoogleMaps/tree/maui

**Comment by AlonRom** [comment]
@themronion this is great! are you planning to continue to support the MAUI version and address issues in the future?

**Comment by amay077** [comment]
Hello everyone.
I'm reborn. :innocent:

(I was writing typescript for several years.
So I lost interest in Xamarin and C#.
But recently I re-started writing C#, which has given me some motivation.)

This project is not died.
I'm deployed [v5.0.0 to nuget](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/5.0.0) that supports Xamarin.Forms 5.0.
And I'm starting understand for MAUI, I will supports it if I can(maybe create new project)。.

**Comment by jari-kuipers** [comment]
Interesting news @amay077 . I think it would be wise to announce your return a little greater than in a comment on an issue that's 2 months old. We've been having a lot of discussions in this project about continuing Xamarin support and all of those discussion's issues need to be closed.

Also, why would you begin working on MAUI? It's been having such a ridiculously rough start.

**Comment by amay077** [comment]
I will support Xamarin.Forms 5 and over .
I'm not sure develop MAUI version soon because I don't understand MAUI's custom control mechanism.

Respect for @themronion and his developed MAUI version.
His package will be good choice for you.

I interest for (stable released) MAUI and .NET 6.
I will developing for MAUI apps/libs at one’s own pace.

**Comment by orwo1** [comment]
It's good to have you back @amay077 !

Regarding MAUI's custom control mechanism, it's not difficult to work with compared to Xamarin.Forms
Renderers, it's just a little different. And the solution/project layout are of course changed completely.

@jari-kuipers  I think it's good to start work on MAUI already since its been in preview for such a long time already,
and I don't see the scheme for custom controls changing from its current state.
Also, when Microsoft will decommission Xamarin.Forms, I would like to know there is a good alternative.

Looking forward to your future releases

**Comment by roubachof** [comment]
@amay077 just so you know, you can still use renderers and migrate to MAUI with very little efforts.
I migrated Sharpnado.CollectionView and changed nearly nothing except for the namespaces and the .net6 target :)

https://github.com/roubachof/Sharpnado.CollectionView/tree/main/Maui

**Comment by themronion** [comment]
@roubachof but does it make any sense since my fork with handlers exists?)

**Comment by roubachof** [comment]
lol didn't see you forked it...
Just saw you have some commits behind though ;)

**Comment by themronion** [comment]
Yeah, it was before @amay077 resurrected))

**Comment by roubachof** [comment]
well now I know it's in good hands :)
