### ISSUE TITLE
Decommissioning supported Maps SDKs

### ISSUE THREAD

**Issue by valliappan16** [amay077/Xamarin.Forms.GoogleMaps#784]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.3.0
* Xamarin.Forms - 5.x.xxxx

### PLATFORMS

- [ ] Android
- [x] iOS
- [ ] UWP

Currently using Xamarin Forms Google Maps API, However, 3.3.0 version gets warning in iOS to use latest Google maps SDK. Need support to avoid this issue in future

<img width="610" alt="Screenshot 2022-02-01 at 11 40 57 AM" src="https://user-images.githubusercontent.com/12950665/151921077-871df2bd-f058-427b-b913-98358edfde24.png">

**Comment by jari-kuipers** [comment]
This is quite concerning.

Let me tell you in advance: This project is dead.
@amay077 has been tagged several times by several threads including my own thread asking if the project is dead [#772](https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/772)

This project is in need of a fork by someone else if it wants to continue existing.

**Comment by themronion** [comment]
@jari-kuipers @valliappan16 here you are mates, i updated the library versions and made a "pirate" nuget. Try it out on your spare time
[Xamarin.Forms.GoogleMaps.4.0.0-BETA2.nupkg.zip](https://github.com/amay077/Xamarin.Forms.GoogleMaps/files/8069645/Xamarin.Forms.GoogleMaps.4.0.0-BETA2.nupkg.zip)

**Comment by AlonRom** [comment]
@jari-kuipers @themronion @valliappan16 are you sure @amay077 is not supporting this package anymore?
Do you have a suggestion for another alternative? Our project is heavily depends on this library :/

**Comment by themronion** [comment]
@AlonRom 99% sure. Try my nuget and let me know if it works fine

**Comment by AlonRom** [comment]
@themronion I don't have a specific issue to test now but we surely need future support.

**Comment by jari-kuipers** [comment]
@AlonRom I am 100% sure. I even tried emailing @amay077 's personal email address on February 1st and I still haven't gotten any response. 

There are no alternatives and other than forking this repo and updating it or trying @themronion 's package, there is nothing you can do.

I suspect that if @amay077 does return, he will only do so to deprecate this package. Maybe you can get him to answer if we all send him emails (if his personal email is still in use).

If you wanna try it for yourself, go ahead and try. His personal email is  #okuokuoku@gmail.com

But to be frank with all of you, you shouldn't be using Xamarin in the first place. All of you should have migrated long ago, which is what we did and we never regretted it. Xamarin will soon be end of life and MAUI has not and will definitely not pick up enough speed to be able to completely replace it by then.

If you "absolutely can't move" which is of course always the case for all of you, then I wish you the best of luck in EOL hell...

**Comment by AlonRom** [comment]
@jari-kuipers that's very unfortunate. can I ask to which technology did you migrate to and do have there all these package capabilities?

**Comment by jari-kuipers** [comment]
@AlonRom I'd be happy to answer that since I did extensive research on this topic for my own company when we had to make the decision to stay with Xamarin or move on to something else.

The best platforms to migrate to are of course the native platforms. You'll have all the support you'll need to upkeep your long-living app for many many years. With Jetpack Compose for Android and SwiftUI for iOS the platforms have evolved thusly that the development speed for them is on par with Xamarin (I would say).

 Lots of companies don't want to invest in this though because of "development and learning costs", often times not realizing the time and money that goes into the upkeep of half-baked apps. 

Also the "benefit" of using C# for everything is not that great. The frameworks and runtimes are different enough to make for quite a learning curve either way. Sure you'll be able to whip up something quickly in Xamarin if you already know C#. But C# and .NET as a whole weren't designed for these types of applications, and you must have noticed the quirks that come with it unless your apps are really simple.

If you really need to have a cross platform app I would highly suggest Flutter for now. It'll have a much longer lifespan than the other cross platform solutions and the development and learning speed is unrivaled by a mile. React-native also wouldn't be the worst choice since it has very mature community support. It's especially useful if you already have people with web dev experience around.

If all of you have medium to large apps that need to live for an extended amount of time with minimal upkeep, then I would seriously look into moving to native applications. You'll also be able to produce better quality apps that way. The investment will be worth it.

**Comment by AlonRom** [comment]
@jari-kuipers Thanks for the comprehensive answer, I thought a lot about moving to NATIVE, but the idea of rewriting the logic twice sounds awful to me, it's something that needs to move from the world in my opinion

**Comment by jari-kuipers** [comment]
@AlonRom does [The official flutter Google maps package](https://pub.dev/packages/google_maps_flutter) not satisfy your needs?

There's also an upcoming framework that you might want to look out for called Kotlin Multiplatform that keeps both iOS and Android in their worth while using shared logic written in Kotlin.

**Comment by AlonRom** [comment]
@jari-kuipers doesn't look like it, we support stuff like clustered icons, custom icons, edit shapes with validations, drag & drop pins, and more. the Flutter project looks very light at this point.

**Comment by john-dalsgaard** [comment]
Just thought I would mention here that there is a fork: https://github.com/INHack20/Xamarin.Forms.GoogleMaps that seems to be maintained :)

**Comment by LittleBoxOfChicken** [comment]
@john-dalsgaard but there hasn't been a commit since 2021 right?

**Comment by john-dalsgaard** [comment]
Right - but it is, however, newer than this.... Predominantly updates to packages so that version may avoid the decomissioning issues. I'm fighting other errors where the app has started crashing when I bind a variable from my view model to `InitialCameraUpdate`. If I leave that out it runs steady... So that is a bigger concern at the moment :-(

**Comment by amay077** [comment]
Hi @valliappan16 ,
I deployed [v5.0.0 to nuget](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/5.0.0).
Could you try it?

https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/783#issuecomment-1232771417
