### ISSUE TITLE
Map, Pin and Shapes BindableProperty support

### ISSUE THREAD

**Issue by amay077** [amay077/Xamarin.Forms.GoogleMaps#9]
`Pin` and Shapes (`Polyline`, `Polygon`, `Circl`) has BindableProperties (ex: `Pin.PositionProperty` ) but these are not implement.

Also I should make `Map.Pins`, `Map.Polygons` ... as bindable.

**Comment by amay077** [comment]
[v1.4.0](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.4.0) contains part of this.
But do not test yet.

**Comment by amay077** [comment]
[@ticktackmobile](https://twitter.com/ticktackmobile/status/755983769295663104) give me interest link for "Readonly" BindableProperty.

* [SetValue(Xamarin.Forms.BindablePropertyKey,System.Object) - Xamarin](https://developer.xamarin.com/api/member/Xamarin.Forms.BindableObject.SetValue/p/Xamarin.Forms.BindablePropertyKey/System.Object/)

**Comment by dreamsystems** [comment]
Hi, it would be nice to implement an `IList<Pin>` BindableProperty to the `map.Pins` property. 
This way, we could do things like this :
`<maps:Map {Binding Pins, Mode=Whatever} />`
For people who work with the MVVM pattern, this feature is pretty essential.
Thanks

**Comment by jdluzen** [comment]
While this is in progress, I have been using a workaround. Since Map only has one `IList<Pin>` instance for the Pin property, I make my own Map2 class (uninspired name I know) with a new `ObservableCollection<Pin>` BindableProperty. Then, everything hooks up with MVVM. And yes, it does depend on the current implementation of Map, but hopefully that will only be temporary.

**Comment by dreamsystems** [comment]
hi, thanks for your suggestion. I am not using the plugin at the moment. It would be nice to have a neat implementation of this feature.

**Comment by amay077** [comment]
Hi @jdluzen,

Would you show me your `Map2` implementation?

**Comment by jdluzen** [comment]
Sure, it's nothing terribly interesting. Though the trick to getting the Pins' getter / setter to be called from XF in the right order is BindingMode.OneWayToSource.
```
public class Map2 : Map
    {
        public static readonly BindableProperty PinsProperty = BindableProperty.Create(nameof(Pins), typeof(ObservableCollection<Pin>), typeof(Map2), null, BindingMode.OneWayToSource);

        public Map2()
        {
            Pins = (ObservableCollection<Pin>)base.Pins;
        }

        public new ObservableCollection<Pin> Pins
        {
            get
            {
                return (ObservableCollection<Pin>)GetValue(PinsProperty);
            }
            set
            {
                SetValue(PinsProperty, value);
            }
        }
```

**Comment by amay077** [comment]
Thanks @jdluzen .
I'll use as reference in my implementation.

**Comment by dreamsystems** [comment]
You can take a look at line 74 for a clean implementation of this feature. It use an 
`IEnumerable<T>` interface instead of an `ObservableCollection<T>`. Even better, 
`IList<T>` provide a more convenience API to developers. 

You probably don't want your users restricted to supply an observable collection.
https://github.com/TorbenK/TK.CustomMap/blob/master/TK.CustomMap/TK.CustomMap/TKCustomMap.cs

**Comment by JeanCollas** [comment]
@dreamsystems @jdluzen  I didn't see this issue earlier. However if you are interested, I implemented it there:

https://github.com/amay077/Xamarin.Forms.GoogleMaps/pull/151

Feel free to suggest improvements :)

**Comment by amay077** [comment]
I recommend to use extension library named [``Xamarin.Forms.GoogleMaps.Bindings``](https://github.com/nuitsjp/Xamarin.Forms.GoogleMaps.Bindings) which provide binding for XAML by Xamarin.Forms behaviors.
